# Typus Roles Configuration File
#
# Use the README file as a reference to customize settings.

admin:
  Comment: create, read, update, delete
  Post: create, read, update, delete
  User: create, read, update, delete
  Vote: create, read, update, delete
